### ISSUE TITLE
unknown option [-o]

### ISSUE THREAD

**Issue by ham1** [fmadio/pcap_flow#4]
I've just taken the latest master and built it, howver I get the following error when trying to use one of the  example commands.

```
 ~/pcap_flow-master/pcap_flows test.pcap --extract-tcp-port 443 443 -o ./port443_
[test.pcap]
[--extract-tcp-port]
     extract all tcp flow with port 443-443
[-o]
    unknown option [-o]
```

The PCAP file certainly has some https flows inside, any thoughts?

**Comment by fmadio** [comment]
theres no -o flag

probably you want

--output-tcp ./port443_

**Comment by ham1** [comment]
Thanks, that fixes it, however you might want to update the README as it lists `-o` in the usage and examples.

**Comment by fmadio** [comment]
Ah understood, thanks
