### ISSUE TITLE
This TCPHeader_t is missing an ipsize len。

### ISSUE THREAD

**Issue by yzlyzlyzl** [fmadio/pcap_flow#6]
![image](https://user-images.githubusercontent.com/19515744/80896955-66220280-8d26-11ea-9aca-d287431bc3e4.png)
hi,fmdio:
I found a problem...
typedef struct
{
	u16			PortSrc;
	u16			PortDst;
	u32			SeqNo;
	u32			AckNo;
	u16			Flags;
	u16			Window;
	u16			CSUM;
	u16			Urgent;

} __attribute__((packed)) TCPHeader_t;
This TCPHeader_t is missing an ipsize len。

**Comment by fmadio** [comment]
IP size is part of the IPv4 header struct

tcp header length can be calculated from Data offset in the flags value
https://en.wikipedia.org/wiki/Transmission_Control_Protocol

**Comment by yzlyzlyzl** [comment]
I cannot access this website....
Below is my definition desc:
struct sniff_tcp {
        u_short th_sport;               /* source port */
        u_short th_dport;               /* destination port */
        tcp_seq th_seq;                 /* sequence number */
        tcp_seq th_ack;                 /* acknowledgement number */
        u_char  th_offx2;               /* data offset, rsvd */
        u_char  th_flags;		/*flags*/
        
        u_short th_win;                 /* window */
        u_short th_sum;                 /* checksum */
        u_short th_urp;                 /* urgent pointer */
};

If there is no th_offx2, is there no problem with the value?
